# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bd9c2bc5f4181e3c9dbe9c25bfb59e682ff7bde880d486e3e6c69927304fb3fb48d808dae87fffed38058ba297aaf4da727f8c2ab61331da9f8d1937afee99b

test:
  secret_key_base: 6a7c3fb166a7dd525464b984dcffc892e11eae80f400867dcac5e3894dbcc139a74837931a711e8b8463f98d702637dcab17d3fc59562a92a4acfa2a2d5809c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
